GoogleContainerTools/distroless

.travis.yml
buildifier.sh

buildifier outputs diffs, but returns an exit code of 0.

Fix the buildifier test.

---

WORKSPACE

udeb's are smaller, stripped down debs that are used as part of the debian installation process.  I'm not sure exactly what the downsides to using them over the regular debs, but it makes the image considerably smaller.  
https://wiki.debian.org/udeb
```
bazel/base:new               1.041 MB
bazel/base:base              14.21 MB
```

Use udeb for base image instead of deb

---

WORKSPACE
base/BUILD
examples/nonroot/BUILD
examples/nonroot/testdata/user.go
examples/nonroot/testdata/user.yaml

This test fails without /etc/passwd or glibc.

Add an image that uses a basic libc call from go.

---

WORKSPACE

This mirror uses a special feature in apt to resolve the nearest debian
mirror through SRV DNS records.
If the client is not capabale of resolving this it will get an http redirect
to the nearest mirror.
See https://deb.debian.org/ for a description

use geo load balancing enabled mirror for apt

---

WORKSPACE
base/BUILD
cacerts/cacerts.bzl
cc/BUILD
java/BUILD
package_manager/BUILD
package_manager/cloudbuild.yaml
package_manager/dpkg.bzl
package_manager/dpkg_parser.py
package_manager/package_manager.bzl
package_manager/parse_metadata.py
package_manager/parse_metadata_test.py
package_manager/testdata/Packages.txt
python2.7/BUILD

These are bazel rules to help resolve remote locations of the .deb
dependencies in our images.
ref #7 
This is a first pass at adding rules that make the .deb resolution more user friendly and less fragile.  No need to resolve the URLs manually and hardcode into an http_rule.  I'm not sure how to really incorporate them in the WORKSPACE, but I imagined something like this in BUILD files.
```
load("//packages:deb_pkg.bzl", "deb_pkg")
load("//packages:deb_src.bzl", "deb_src")
deb_pkg(
name = "openssl",
pkg_name = "openssl",
source = ":debian_jessie",
)
deb_src(
name = "debian_jessie",
arch = "amd64",
distro = "jessie",
mirror_url = "http://httpredir.debian.org",
)
```
then you can reference the debs in your docker_rule by 
```
docker_build(
name = "base",
base = ":with_tmp",
debs = [ …
```

dpkg and dpkg_src rules for deb packages

---

README.md

add missing link to docker multi-stage build documentation.

README.md: add link for multi-stage builds

---

WORKSPACE

This fixes #65 
In CI we run with   `bazel test --test_output=errors //...`, which serializes test execution. There was a bug in structure tests which made parallel executions fail. This fixes that bug.

Update structure_test to pick up fix for parallel execution.

---

README.md
WORKSPACE
base/BUILD
cacerts/cacerts.bzl
cc/BUILD
java/BUILD
package_manager/BUILD
package_manager/README.md
package_manager/dpkg.bzl
package_manager/dpkg_parser.py
package_manager/package_manager.bzl
package_manager/parse_metadata.py
package_manager/parse_metadata_test.py
package_manager/testdata/checksum.txt
package_manager/util.py
package_manager/util_test.py
python2.7/BUILD

* Allows multiple sources on the dpkg() rule
Sources will be tried in the order they appear.  For different priority, split up your package bundles into different dpkg rules.
* Automatically renames packages that are not valid bazel rule names.
Prints out a warning with instructions on how to reference the resulting deb.  The best solution I can think of here is to eventually output a tarball of deb packages.  Then, the output wouldn't have to be the individual deb files (which for some packages won't be able to be referenced by bazel labels).
* Allows multiple packages to be part of the same dpkg() rule
* Bumps version of dpkg_parser.par to v0.2
Fixes https://github.com/GoogleCloudPlatform/distroless/issues/70
Partially addresses  #68

Refactor dpkg rules

---

.travis.yml
test.sh

Makes it easier to run the full travis suite locally.
Added the Google copyright header to this file since its in the GoogleCloudPlatform org.  Is that right @dlorenc?

Move test commands to script

---

java/BUILD

This removes some of the guesswork about where the Java binary is in derivative layers.

Add the standard /usr/bin/java symlink.

---

WORKSPACE
examples/go/BUILD
examples/java/BUILD
examples/java/testdata/hello.yaml
examples/nonroot/BUILD
examples/nonroot/testdata/user.yaml
examples/python2.7/BUILD

PoC that consumes the `foo_image` rules I'm adding in [this PR](https://github.com/bazelbuild/rules_docker/pull/98).

Update the distroless examples to utilize the new contrib image rules.

---

cacerts/BUILD

I need this over in debian-docker.

Make cacerts public.

---

WORKSPACE

This bumps the go version used.

Update bazel go rules

---

WORKSPACE

This is easier to reason about the current version used and to find it online than a commit hash.

Update runtimes_common repository

---

package_manager/dpkg_parser.py
package_manager/package_manager.bzl

This PR adds simple version capability to dpkg_parser.py  With this PR, versions can now be specified using the syntax "package=<VERSION>":
packages = [
"libc6=VERSION",
"libwsutil-dev=2.2.4+gcc3dc1b-1~bpo8+1",
"ca-certificates", # old syntax is still preserved
],
The old syntax of just using the package name is still preserved and works as it did previously.
NOTE:  Currently the version specified much exactly match the version value in the Packages.gz file.

added simple version capability to dpkg_parser

---

base/BUILD
base/testdata/base.yaml
package_manager/dpkg.bzl
package_manager/dpkg_parser.py
package_manager/package_manager.bzl
package_manager/util.py
package_manager/util_test.py

Adds another output file to the dpkg_src rule with os-release-like
metadata about the distribution
Add a structure test validation for /etc/os-release in the base image

Add /etc/os-release file generation package rules

---

WORKSPACE

Version 0.5.5 contains a bugfix for dependency checksums.
see https://github.com/bazelbuild/rules_go/releases/tag/0.5.5

Update rules_go version

---

WORKSPACE
cacerts/java.bzl
java/BUILD
java/testdata/CheckCerts.java
java/testdata/certs.yaml
java/testdata/java.yaml

Add a rule to generate java cacerts files using a debian docker image.

---

WORKSPACE

The url parameter in http_file and new_http_archive rules is deprecated.
See https://docs.bazel.build/versions/master/be/workspace.html#http_file etc.

replace url with urls in WORKSPACE rules

---

base/BUILD

Omitting PATH seems to make Docker default to a typical value, but when we add `busybox` we block this.
This gives `//base` the typical value, and makes `//base:debug` extend it to include `/busybox`.

This corrects the PATH in debug images.

---

package_manager/dpkg_parser.py
package_manager/parse_metadata.py
package_manager/parse_metadata_test.py

This PR adds two new attributes to the dpkg_parser tool:
- packages_gz_url: full url to the Packages.gz file
- package_prefix: prefix to append to the value of "Filename" in the
Packages.gz file (e.g. pool/main/n/newmail/newmail_0.5-2_amd64.deb)
These two new attributes should always be used together, and when they
are specified, attributes url, snapshot, distro and arch will be
ignored.

Support passing complete url of Packages.gz file in dpkg_parser.

---

package_manager/README.md
package_manager/dpkg.bzl
package_manager/package_manager.bzl

Now dpkg_src rule supports retrieving Packages.gz file from arbitrary urls.

Add packages_gz_url and package_prefix in the dpkg_src rule.

---

base/BUILD
cacerts/cacerts.bzl

The current structure requires a `dpkg_list` named `package_bundle` to
always exist in the WORKSPACE file, which is not ideal if `dpkg_list` for
multiple distros (e.g. jessie, trusty, xenial) are declared at the same time.

Remove hardcoded @package_bundle repo in cacerts.bzl.

---

WORKSPACE

In theory, this should help support better cross compilation for things
like GoogleCloudPlatform/distroless#133.

Update to the latest `rules_go` release

---

BUILD.dotnet
BUILD.jetty
BUILD.nodejs

The former is supported, while the latter is deprecated:
https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar

Use `srcs` instead of `files` in pkg_tar rules

---

BUILD
BUILD.dotnet
BUILD.jetty
BUILD.nodejs
README.md
WORKSPACE
examples/python3/BUILD
examples/python3/hello.py
python3/BUILD
python3/README.md
python3/testdata/python3.yaml

This should help with GoogleCloudPlatform/distroless#111 and
bazelbuild/rules_docker#229.
A few of caveats:
* This still needs to be uploaded to gcr.io, presumably by some automated
process that I'm not privy to.
* This only tests importing a single module from the standard library
(as with the 2.7 image).  I suspect there may be other dependencies
which are required for other modules in the standard library; it
would be nice to have tests for importing other modules which require
additional dependencies.
* Since the distroless base image is currently based on Debian Jessie, this
uses version 3.4.2.  Ideally, we'd update distroless to be based on
Stretch, and the newer versions of the dependent packages (across the
board).  I suspect this would require some additional qualification
on …

Add a python3 distroless image 

---

BUILD.dotnet
BUILD.jetty
BUILD.nodejs
WORKSPACE

Fixes #116 
New image sizes:
nodejs: 75.1MB from 93MB
jetty: 143MB from 161MB
dotnet: 117MB from 143MB

Remove the .tar.gz's from the dotnet, jetty and nodejs images.

---

nodejs/README.md

As of #127 the distroless nodejs image is using version 8. I updated the readme to reflect that change.

Update node.js version in README.md

---

base/BUILD
cc/BUILD
dotnet/BUILD
java/BUILD
nodejs/BUILD
python2.7/BUILD
python3/BUILD

Fixed inconsistency between openssl and libssl.so.
I checked the following behavior, I'm not familiar with Bazel, though.
```
$ PROJECT_ID=tmp bazel build :all
$ PROJECT_ID=tmp bazel run all
$ docker run -it gcr.io/lovot-services-dev/base:debug
/ # openssl version
OpenSSL 1.1.0f  25 May 2017
/ # find / | grep libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
```
```
$ bazel test --test_output=errors //...
INFO: Analysed 69 targets (26 packages loaded).
INFO: Found 56 targets and 13 test targets...
INFO: Elapsed time: 17.621s, Critical Path: 16.82s
INFO: Build completed successfully, 264 total actions
//base:base_test                                                         PASSED in 3.5s
//base:certs_test                                                        PASSED in 2.5s …
```

Fix consistency between openssl and libssl.so (#169)

---

WORKSPACE
package_manager/README.md

The dpkg_list rule finds the first package from the sources attribute.
Previously the order was debian, backports, security. This means the security
updates were never applied. This switches the order and updates the snapshot
to the latest version.
The following packages are different after reordering:
```
openjdk-8-jre-headless: 8u151-b12-1~deb9u1 -> 8u162-b12-1~deb9u1
openssl 1.1.0f-3+deb9u1 -> 1.1.0f-3+deb9u2
libcurl3 7.52.1-5+deb9u4 -> 7.52.1-5+deb9u5
libc6 2.24-11+deb9u3 -> 2.24-11+deb9u1 *** older version!
libicu57 57.1-6+deb9u1 -> 57.1-6+deb9u2
libssl1.0.2 1.0.2l-2+deb9u2 -> 1.0.2l-2+deb9u3
libssl1.1 1.1.0f-3+deb9u1 -> 1.1.0f-3+deb9u2
libuuid1 2.29.2-1 -> 2.29.2-1+deb9u1
```
*** Note: libc6 indicates that dpkg_parser should parse and compare versions.
This is a security release …

WORKSPACE: Update Debian packages; Order security updates first

---

package_manager/dpkg_parser.py

In clean builds of our project (three package sources, ~100 imported dpkgs), `dpkg_list` is by far the slowest part at 4-5 minutes.  I found these two changes vastly speed up the dpkg parser; the time is now dominated by downloading the packages, instead of being CPU-bound in python.  The `dpkg_list` for our build now takes 0:45-1:30, a substantial improvement.
Thanks for taking a look.

package_manager: two optimizations in `dpkg_list`

---

package_manager/package_manager.bzl

This brings in the changes from https://github.com/GoogleContainerTools/distroless/pull/204 to be used at runtime.

package_manager: update par binary source

---

WORKSPACE
base/BUILD
examples/dotnet/BUILD
examples/java/BUILD
examples/nodejs/BUILD
examples/nonroot/BUILD
experimental/busybox/BUILD
experimental/python2.7/BUILD
experimental/python3/BUILD
java/BUILD

This PR just upgrades to the latest version of `rules_docker` with the goal of allowing packages from Debian Buster now that https://github.com/bazelbuild/rules_docker/commit/7401cb256222615c497c0dee5a4de5724a4f4cc7 is landed (i.e., unblocking Python 3.6 🙂).
`rules_docker` these days adds `runtimes_common` when `structure_test` is not already defined, now that `structure_test` was moved to its own repo. Unfortunately, the rule in `structure_test` has an invalid label in one of its implicit dependencies (likely from the repo move), so this commit also refactors the users of `structure_test` to now use the still-working `container_test` from `rules_docker` anyway.

Upgrade rules_docker to latest revision

---

README.md

https://github.com/docker-library/golang/pull/205
And removed from >=1.9 images

go-wrapper functionality is deprecated

---

experimental/nodejs/README.md

The example link in a deep readme is off by one directory.

Same as #210 and #213 broken link

---

experimental/python3/README.md

Just like in #210 the link for Python 3 example is off one directory.

Examples Link, Same as #210

---

WORKSPACE
experimental/python2.7/BUILD
experimental/python2.7/testdata/python27.yaml
experimental/python3/BUILD
experimental/python3/testdata/python3.yaml

The Python standard library includes os.system and Popen.subprocess which
can both take a string argument, which then executes that string in a
shell. Add dash so /bin/sh exists and the standard library works.
Argubly using /bin/sh in this way is dangerous and deprecated, but parts of
the standard library itself rely on this (e.g. ctypes). I suspect there are
many Python programs "in the wild" that do as well. If the goal of the
default base image for rules_docker and distroless is to reliably run any
Python program, it should support this, since this is part of the standard
library. The additional ~200 kiB seems worth the additional compatibility.
Found while investigating
https://github.com/GoogleContainerTools/distroless/issues/150

python: Add dash so os.system and Popen.subprocess work

---

README.md

Since they're isted in the first list, I guess it's stable, and shouldn't be in the second list of experimental images.

Remove duplicate listing for gcr.io/distroless/(java|cc)

---

WORKSPACE

Includes a fix to openjdk, curl and maybe others I didn't notice. This
might also pick up newer backports.
Use https to access snapshot.debian.org.
DSA-4286 curl: https://www.debian.org/security/2018/dsa-4286
DSA-4268 openjdk-8: https://www.debian.org/security/2018/dsa-4268

WORKSPACE: Update Debian snapshot for security fixes.

---

WORKSPACE

The important updates are probably the Python security fix:
https://www.debian.org/security/2018/dsa-4306
https://www.debian.org/security/2018/dsa-4307
This updates at least the following packages.
Python2.7 goes from 2.7.13-2+deb9u2 to 2.7.13-2+deb9u3
```
libpython2.7-minimal
libpython2.7-stdlib
libpython3.5-minimal
libpython3.5-stdlib
python2.7-minimal
python3.5-minimal
```

WORKSPACE: Latest security fixes (Python)

---

WORKSPACE

Commit b35d94bc3d added libc-bin to the Python image. Since dpkg_parser
does not parse and compare versions, it is getting the most recent
version from debian_security, which is an older pre-release security fix,
rather than the released version. To fix it, ask for the right version.
A similar issue was fixed for libc6 itself in 6f5345dd25.
Updates libc-bin from 2.24-11+deb9u1 to 2.24-11+deb9u3
Found by the Google Cloud container security scanner.

WORKSPACE: Update libc-bin to latest released version (security)

---

BUILD
README.md
base/BUILD
base/README.md

This image is like base, but has even fewer dependencies. Notably, the following packages are removed:
- libc
- openssl

Add a distroless "go" base image.

---

WORKSPACE

This includes a security fix to OpenSSL released on 2018-11-30:
https://www.debian.org/security/2018/dsa-4348
This is reported as a vulnerability by the Google Cloud container
security scanner.

WORKSPACE: Update to latest Debian snapshot

---

cloudbuild.yaml

This is awful but it seems like the fastest way to get pushes going again.

push_all is completely broken, use cloudbuild.yaml instead.

---

hack/print-workspace-status.sh

@dlorenc can you give me the owner (committer, or whatever) access?
```
$ ./hack/print-workspace-status.sh
./hack/print-workspace-status.sh: line 9: [: which: unary operator expected
PROJECT_ID NO-PROJECT
```

Fix bash script

---

BUILD
README.md
WORKSPACE
base/BUILD
cacerts/java.bzl
cc/BUILD
examples/dotnet/BUILD
examples/nodejs/BUILD
examples/nonroot/BUILD
examples/python2.7/BUILD
examples/python3/BUILD
experimental/dotnet/BUILD
experimental/dotnet/README.md
experimental/nodejs/BUILD
experimental/python2.7/BUILD
experimental/python3/BUILD
java/BUILD
java/jetty/BUILD
package_manager/README.md

Building, testing, and publishing all work. But I admit I've never used these rules before, so I am not strong on pushing this soon. But turns out, this also fixes [the broken `blaze run :publish`](https://github.com/GoogleContainerTools/distroless/pull/263).

Migrate docker rules

---

WORKSPACE

`openjdk-11` was back-ported to Debian "stretch" quite recently, and the Java 11 landscape is changing fast as we approach the end of January. Therefore, although the previous stretch-packports snapshot included `openjdk-11`, I think it's good to advance the snapshot.
~~This PR also reads in `openjdk-11-jre-headless` for later use.~~

Pull the newest snapshot

---

WORKSPACE
examples/nodejs/Dockerfile
experimental/nodejs/README.md

https://nodejs.org/en/blog/vulnerability/november-2018-security-releases/
Fixes for the following CVEs are included in this release:
- Node.js: Denial of Service with large HTTP headers (CVE-2018-12121)
- Node.js: Slowloris HTTP Denial of Service (CVE-2018-12122 / Node.js)
- Node.js: Hostname spoofing in URL parser for javascript protocol (CVE-2018-12123)
- Node.js: HTTP request splitting (CVE-2018-12116)
- OpenSSL: Timing vulnerability in DSA signature generation (CVE-2018-0734)
- OpenSSL: Microarchitecture timing vulnerability in ECC scalar multiplication (CVE-2018-5407)

Upgrade NodeJS to the latest Carbon LTS (v8.15.0)

---

package_manager/dpkg_parser.py

#276 and #214 request branding the distroless/java images with metadata about the underlying language runtime version. Unfortunately the package information is not available when building the image: all that is available is the actual `.deb` file.
https://github.com/GoogleContainerTools/distroless/blob/55b0eb29ae8228e59ec14b02ca6b904c20340f06/java/BUILD#L12-L17
Rather than try to extract the `.deb`'s `control.tar.gz` and its `control` file, this PR changes the `package_manager` to also record a package-to-version mapping (`versions`) that is written out with the `@package_bundle//file:packages.bzl`.
The resulting `packages.bzl` file now looks like:
```
packages = {"libgcc1": "@package_bundle//file:bGliZ2NjMQ==.deb", "libgomp1": "@package_bundle//file:bGliZ29tcDE=.deb", ... }
versions = …
```

Maintain package version mapping

---

java/BUILD
java/jre_ver.bzl
java/testdata/java11.yaml
java/testdata/java11_debug.yaml
java/testdata/java8.yaml
java/testdata/java8_debug.yaml
package_manager/dpkg_parser.py
package_manager/package_manager.bzl

#276 requests that the `java` images provide information as to the JRE version. This PR follows on from #290 and adds the following metadata to the `distroless/java` images:
- it sets a `JAVA_VERSION` environment variable to the JRE version, currently `8u181` for the Java 8 image and `11.0.1` for the Java 11 image
- ~~it sets three labels:~~
- ~~`jdk.vendor` is hard-coded to `openjdk` since we explicitly select the `openjdk-*-jre-headless` packages~~
- ~~`jdk.version` is the same release number reported in `JAVA_VERSION`~~
- ~~`jdk.source` records soe provenance information listing the Debian package name and version: currently `openjdk-8-jre-headless 8u181-b13-2~deb9u1` and `openjdk-11-jre-headless 11.0.1+13-2~bpo9+1`~~
_Update: I'm not convinced of these label keys, and since …

Record JRE version details in Java image metadata

---

WORKSPACE

This appears to be the new "maintained" Maven repository URL. At the very
least it is the URL that Bazel itself uses:
https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/maven_rules.bzl

WORKSPACE: Use https for Jetty: https://repo1.maven.org

---

java/BUILD
java/testdata/java8.yaml
java/testdata/java8_debug.yaml

Update Java 8 images to use `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`.
Fixes #289

Use container-friendly arguments for Java 8 images

---

java/BUILD
java/testdata/java8.yaml
java/testdata/java8_debug.yaml

I have significant misgivings about using `_JAVA_OPTIONS`: as `java` outputs even when the variable is an empty string, and it's hard to unset an environment variable once set:
```sh
$ set _JAVA_OPTIONS=-Xms45m
$ _JAVA_OPTIONS="" java -version
Picked up _JAVA_OPTIONS: 
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```
I fear this will break tests and tools that expect to produce useful output.
This PR reverts to my first approach in #295 and passes the container-friendly arguments on the command-line, fixing #289.  It's not as inheritable, but it doesn't change behaviour.

Rework #295 to specify container-friendly args in entrypoint

---

WORKSPACE
java/BUILD

Fixes #300.
[`libjpeg62-turbo` provides `libjpeg.so.62`.](
https://packages.debian.org/stretch/amd64/libjpeg62-turbo/filelist)

Add libjpeg62-turbo Debian package to Java images

---

WORKSPACE
java/testdata/java11.yaml
java/testdata/java11_debug.yaml

Update libc from 2.24-11+deb9u3 -> 2.24-11+deb9u4. This is a
"regular" update, and not a security update, so we still need the hack to
force the latest version to be resolved instead of the older version in
the stretch-security release.
However, this does fix some low priority CVEs that are reported by the
Google Cloud container vulnerability scanner. See:
https://metadata.ftp-master.debian.org/changelogs//main/g/glibc/glibc_2.24-11+deb9u4_changelog
This also updates the following packages to their latest versions:
base-files
curl
libc-bin
libc6
libcurl3
libldap-2.4-2
libldap-common
libsqlite3-0
openjdk-11-jre-headless
tzdata

WORKSPACE: Latest Debian snapshot. Update libc6 to

---

BUILD
cloudbuild.yaml
java/jetty/BUILD
java/jetty/testdata/java11.yaml
java/jetty/testdata/java11_debug.yaml
java/jetty/testdata/java8.yaml
java/jetty/testdata/java8_debug.yaml

[We install Jetty 9.4.14](https://github.com/GoogleContainerTools/distroless/blob/master/WORKSPACE#L162), and it should be stable on Java 11 runtimes. 
https://www.eclipse.org/lists/jetty-announce/msg00125.html
https://webtide.com/java-updates-jetty-and-the-future/
Verified its actual working with a tiny example.

Build Jetty-on-Java 11 images

---

base/BUILD
base/testdata/base.yaml

This PR is purely cosmetic and adds two entries to `/etc/group` for `staff` (gid 50) and `tty` (gid 5).
distroless/base configures `/etc/group` to only include a `root` group.  But Debian's `base-files` package adds `/var/local` which is owned by `0:50`, and `/dev/console` and `/dev/pts/0` have group `5`.  In Debian, group 5 is `tty` and group 50 is `staff`.
----
`busybox`'s `find` doesn't support `-nouser` nor `-nogroup`, but the following command verifies there are no other unowned files or directories:
```
$ find / \! \( -user 0 -a \( -group 0 -o -group 5 -o -group 50 \) \) -exec ls -l {} \;
```

Add group entries for `staff` and `tty`

---

.travis.yml
WORKSPACE

Bump snapshot URLs for CVEs.

---

WORKSPACE
java/BUILD
java/testdata/java8.yaml
java/testdata/java8_debug.yaml

Fixes #293 #331.
Locally built Java 8 shows 8u212. Yeah!
```
$ docker run --rm bazel/java:java8_debug -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

Update snapshots to pull in latest Java 8 (8u212)

---

.travis.yml
BUILD
buildifier.sh

Change `buildifier.sh` to run with `-mode=diff` to report suggested changes.  Requires updating to 0.22.0 so `-mode=diff` errors on change.
Example of failure at https://travis-ci.org/GoogleContainerTools/distroless/builds/511137529 (raw log: 
https://api.travis-ci.org/v3/job/511137530/log.txt)

Make buildifier be helpful

---

buildifier.sh

On my machine, I have `DISPLAY=:0` defined, and seems like `buildifier` tries to be smart to bring up a GUI diff (`/usr/bin/tkdiff`), which is annoying.
```
$ ./buildifier.sh 
buildifier: selecting diff program with the BUILDIFIER_DIFF, BUILDIFIER_MULTIDIFF, and DISPLAY environment variables is deprecated, use flags -diff_command and -multi_diff instead
./base/BUILD:
/usr/bin/tkdiff: 37: exec: /usr/local/old_symlinks/tkdiff: Required key not available
exit status 2
Run 'buildifier -mode=fix $(find . -name 'BUILD*' -o -name 'WORKSPACE*' -type f)' to fix formatting
```

Set -diff_command to use command-line diff tool when calling buildifier

---

.travis.yml
WORKSPACE
cacerts/java.bzl

Fixes #342.
Note we have tests to connect to www.google.com, such as [this](https://github.com/GoogleContainerTools/distroless/blob/master/java/testdata/java8_certs.yaml).

Update image to extract java ca certs

---

WORKSPACE

`buildifier.sh` was complaining with missing commas. I made them one-liners, and it's happy.
```diff
$ ./buildifier.sh
./WORKSPACE:
--- ./WORKSPACE 2019-05-10 18:35:53.814959377 -0400
+++ /tmp/buildifier-tmp-667848469       2019-05-10 18:36:53.370703568 -0400
@@ -17,13 +17,12 @@
load(
"//package_manager:package_manager.bzl",
-    "package_manager_repositories"
+    "package_manager_repositories",
)
-
load(
"//package_manager:dpkg.bzl",
"dpkg_list",
-    "dpkg_src"
+    "dpkg_src",
)
package_manager_repositories()
```

Fix formatting

---

README.md
examples/go/Dockerfile

The latest version Go 1.12 was released on 25 February 2019 and around 2.5 months passed since then.
- https://blog.golang.org/go1.12
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

Update Golang version to 1.12 in examples

---

base/BUILD
examples/nonroot/BUILD

Go binary was being compiled with `darwin` GOOS. We should use Linux since this binary runs in a Linux Container.

fix container_tests on darwin

---

cacerts/cacerts.bzl
cacerts/java.bzl
package_manager/dpkg.bzl

Fixes for:
- --incompatible_new_actions_api
- --incompatible_disable_deprecated_attr_params
- --incompatible_no_support_tools_in_action_inputs
- --incompatible_string_join_requires_strings

Fix breaking changes from Bazel 0.27

---

WORKSPACE

Finally, [rules_docker 0.8.0](https://github.com/bazelbuild/rules_docker/releases/tag/v0.8.0) was released today.

Upgrade to rules_docker 0.8.0

---

.travis.yml
WORKSPACE
package_manager/parse_metadata.py
test.sh

Builds were failing with latest Bazel releases.
Also needed `--host_force_python=PY2` as in [#383](https://github.com/GoogleContainerTools/distroless/pull/383/files). See https://github.com/bazelbuild/rules_docker/issues/842#issuecomment-504143568 for reference.
And now Bazel seems to recognize Python source files under `package_manager` as Python 3 code. `decode('utf-8')` is unnecessary in Python 3: https://stackoverflow.com/a/28583969/1701388. Initially I tried `srcs_version = "PY2ONLY"` for `py_library`, but Bazel said Python 2 and 3 are mixed in source.

Fix build for latest Bazel releases

---

package_manager/package_manager.bzl

Symbols loaded by load() are no longer visible externally, so they need to be re-exported
with an assignment.

Bazel 0.28 fixes

---

README.md
examples/go/Dockerfile

- Update of the readme regarding the entrypoint considerations: proper quotes and clarification for the CMD command when entrypoint is not set.
- Fix for the Golang sample Dockerfile

Documentation fix

---

WORKSPACE
base/BUILD
base/base.bzl
cc/BUILD
experimental/python2.7/BUILD
experimental/python2.7/generate_ldconfig_cache.py
experimental/python2.7/testdata/debian10.yaml
experimental/python2.7/testdata/debian9.yaml
experimental/python2.7/testdata/python27.yaml
experimental/python3/BUILD
experimental/python3/testdata/debian10.yaml
experimental/python3/testdata/debian9.yaml
experimental/python3/testdata/python3.yaml

This adds explicit -debian9 suffixes to the base, cc, and python
packages, with aliases for compatibility.
python2.7: Add support for -debian9 and -debian10
python3:
* add libmpdec2, libdb5.3: required by the standard library, and
was previous missing. I think this is because the standard library
modules include fallbacks in case the native modules are missing.
* add tests for native code _dbm, _decimal to ensure we use native libs
* remove tests for dummy_threading: deprecated and does not work on
Debian 10
* remove test for idlelib: Not installed by default (requires
idle-python3.7). This also needs X11, so doesn't seem to make sense.
* remove test for lib2to3 and macurl2path: does not exist in 3.7
Another part of adding Debian 10 support (Issue #385)

debian10 support: Support Python2.7; Fix Python3; -debian9 suffix

---

cloudbuild.yaml

This supports the base, cc, and python images.
This keeps the existing containers, but adds -debian9 and -debian10
variants. I wrote a script to generate cloudbuild.yaml, which I can
add, or will submit if this change is merged, since managing this
manually is now challenging.
This depends on my changes to add the -debian9 suffix.
I tested this by publishing these images to my own project. You can
test images:
gcr.io/distroless-dev/python3-debian10

cloudbuild.yaml: Publish -debian9 and -debian10 images

---

WORKSPACE

The GCP container security scanner is now reporting some
vulnerabilities in Distroless packages. This update should fix them.
2019-10-01 openssl openssl1.0
https://security-tracker.debian.org/tracker/CVE-2019-1563
https://security-tracker.debian.org/tracker/CVE-2019-1547
2019-09-22 expat
https://security-tracker.debian.org/tracker/CVE-2019-15903

WORKSPACE: Update debian9 and debian10 for latest security updates

---

README.md

Hi Distroless, 
Thanks for documenting the `:debug` option to allow troubleshooting with a shell, very helpful. It wasn't very obvious to me from the README.me how to apply the debug tag to an image that already has a tag, like `gcr.io/distroless/java:11`. 
I thought adding a dash would help and it worked, but I'm not sure if this is the recommended way to do this. Opening this PR to start some discussion.

Mention how to append the debug tag when an image has a tag already

---

package_manager/parse_metadata.py
package_manager/parse_metadata_test.py

I attempted to update the version of package_manager to the latest,
since I noticed the line numbers in error messages did not match. I
got the following error, which I think this change should fix.
The problem is that dpkg_parser calls this function with the output
of gzip.open(path, 'rb'), so the input is binary (python3 str). To
fix it, convert the data argument from binary to text if necessary.
```
dpkg_parser command failed: Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "dpkg_parser/file/downloaded/__main__.py", line 196, in <module>
File "dpkg_parser/file/downloaded/__main__.py", line 77, in main
File …
```

package_manager: Py3 fix: parse_package_metadata processes strings

---

experimental/python2.7/BUILD
experimental/python2.7/testdata/python27.yaml
experimental/python3/BUILD
experimental/python3/testdata/python3.yaml

By default modern Linux systems use UTF-8 for encoding file names,
although AFAICS that is controlled by the LANG environment variable
and some other things. However, Python programs that run on Debian or
Ubuntu may expect this to work. The upstream Docker Python image sets
these environment variables. We should as well. See:
https://github.com/docker-library/python/blob/35566cb6b14961c369e935b85b4c8879e6901ccc/2.7/buster/Dockerfile
* Add tests for file system encoding and the print() function.
* Set LANG=C.UTF-8 for both Python3 and Python2.7
* Set PYTHONIOENCODING=UTF-8 for Python2.7 (not neeeded on Python3)

python: Set LANG=C.UTF-8; python2.7: PYTHONIOENCODING=UTF-8

---

buildifier.sh
cacerts/cacerts.bzl
cacerts/java.bzl
java/jre_ver.bzl
package_manager/dpkg.bzl
package_manager/package_manager.bzl

Enforce auto-formatting on all Starlark files.
I noticed that the existing .bzl files were not auto-formatted while I was editing one of them. I'm assuming this is probably not intentional? Changing the .sh file causes the TravisCI build to break, so this will enforce this for future changes. See the failed build for the version that changed `buildifer.sh` but did not apply formatting: https://travis-ci.org/GoogleContainerTools/distroless/builds/576462638

buildifier.sh: Format .bzl files as well as BUILD and WORKSPACE

---

WORKSPACE
examples/nodejs/Dockerfile
experimental/nodejs/README.md

Node v8 has moved to maintenance LTS and v10 has moved to active LTS. Version `10.16.3` is now the latest active LTS version of Node js.
> It was [released](https://nodejs.org/download/release/latest-v10.x/) on the 15th of August. View the list of [deprecations](https://nodejs.org/en/blog/release/v10.0.0/#deprecations) from node 8 to node 10.

Upgrade node image to latest LTS v10

---

.travis.yml
WORKSPACE
base/testdata/debian10.yaml
package_manager/package_manager.bzl

Corrects the VERSION variable in /etc/os-release
Commit c127f3e5f3 added support for Debian 10 (buster) to
package_manager. Due to the way WORKSPACE dependencies work, we
need this update to actually use the new version.
I also needed to update the version of rules_docker to avoid a Python3
error. This could be because I'm using the latest version of bazel,
but seems like a good idea also.

package_manager.bzl: Use newest version to support Debian 10

---

README.md

The documentation refers to Debian 9 (stretch) as stable, but it is now
oldstable. Add a note that users should explicitly build with the right
"base" Debian distribution corresponding to their distroless images.

README.md: Update to reference Debian 9 and 10

---

WORKSPACE
java/BUILD
java/jetty/BUILD
java/testdata/java11_certs_debian10.yaml
java/testdata/java11_certs_debian9.yaml

This adds Debian 10 support for the Java packages. I did not perform
any testing, beyond ensuring that bazel test //... works, since I do
not actually use Distroless for any Java packages myself.
Since Debian 10 (buster) only includes java11, this only changes it
for those packages.

java: Add _debian9 and _debian10 package versions

---

WORKSPACE
examples/nodejs/Dockerfile
examples/nodejs/node-express/Dockerfile
examples/nodejs/node-express/package.json

[v10.17.0 Release Notes](https://nodejs.org/en/blog/release/v10.17.0/)
- Invalid npm package name for Express example
- Missing `npm install` step
- Aligns Node build environment version with Distroless

Upgrade Node.js to latest v10 LTS

---

WORKSPACE
java/BUILD
java/jetty/testdata/java11.yaml
java/jetty/testdata/java11_debug.yaml
java/jetty/testdata/java8.yaml
java/jetty/testdata/java8_debug.yaml
java/testdata/java11.yaml
java/testdata/java11_debug.yaml
java/testdata/java8.yaml
java/testdata/java8_debug.yaml

Include JVM instrumentation binaries in the distroless/java debug image.

---

WORKSPACE
experimental/python3/BUILD
experimental/python3/testdata/python3.yaml

With Debian 10 buster, the python3 package only includes a partial
version of the distutils package. This causes virtualenv to create
a somewhat broken virtualenv, which causes the following import
error when attempting to use it. This fixes the error by installing
the full version from the standard library. Add a test to ensure
it continues to work.
Fixes the following error:
ImportError: cannot import name 'dist' from 'distutils'

python3 debian10: Install full version of distutils for virtualenv

---

WORKSPACE

The GCP security scanner is warning about issues with python2.7 and
ncurses. Fixes were released on 2019-10-11 and 2019-11-02, after the
last update. Debian 9 (stretch) does not seem to have fixes for these
issues.
ncurses: https://security-tracker.debian.org/tracker/CVE-2019-17595
python2.7: https://security-tracker.debian.org/tracker/CVE-2019-16056
The version updates for all packages in Debian 10 were:
base-files 10.3+deb10u1 -> 10.3+deb10u2
libfreetype6 2.9.1-3 -> 2.9.1-3+deb10u1
libncursesw6 6.1+20181013-2+deb10u1 -> 6.1+20181013-2+deb10u2
libpython2.7-minimal 2.7.16-2 -> 2.7.16-2+deb10u1
libpython2.7-stdlib 2.7.16-2 -> 2.7.16-2+deb10u1
libtinfo6 6.1+20181013-2+deb10u1 -> 6.1+20181013-2+deb10u2
python2.7-minimal 2.7.16-2 -> 2.7.16-2+deb10u1
tzdata 2019b-0+deb10u1 -> 2019c-0+deb10u1

WORKSPACE: Update to latest Debian for security fixes

---

examples/python3-requirements/Dockerfile
examples/python3-requirements/README.md
examples/python3-requirements/psutil_example.py
examples/python3-requirements/requirements.txt

This does not build with Bazel, so it is not currently covered by the
TravisCI test.

python3-requirements: Example that uses third-party dependencies

---

cloudbuild.yaml

I've already cleaned up the `BUILD` file in #430 that can now publish Java Debian 10 images.
Now I only need to do this on the `cloudbuild.yaml` file, and we should be good.
However, I realized the problem that `cloudbuild.yaml` cannot have more than 100 steps. @donmccasland can we break it up into two files, `cloudbuild1.yaml` and `cloudbuild2.yaml`?

Publish Java Debian 10 images (Java 11 only)

---

package_manager/BUILD
package_manager/cloudbuild.yaml
package_manager/package_manager.bzl

Turns out this is unnecessary.
I have confirmed building and publishing all images by
1. First building and uploading this PAR to a temporary bucket.
2. Updating WORKSPACE to use the new PAR, which required updating the SHA of the binary.
3. Build and publishing Distroless images on GCB (to my GCP project).

Reduce visibility of package_manager

---

package_manager/package_manager.bzl

Because of the "two-step" build, when updating dpkg_parser, we can change the URL only after the binary with the change is built.
In #469, I uploaded the new binary too early (and replaced the old one, which was my mistake). So the following binaries have the same SHA, and there's no need to update SHA in this PR.
https://storage.googleapis.com/distroless/package_manager_tools/0e7095cc1ac3e084a1d76f86c36f8ec38483eb24/dpkg_parser.par
https://storage.googleapis.com/distroless/package_manager_tools/1b8448ea6f55db64ea3c1956d4dd1b9c47166a8c/dpkg_parser.par

Use the newly built dpkg_parser binary

---

WORKSPACE
java/testdata/java11.yaml
java/testdata/java11_debug.yaml
java/testdata/java8.yaml
java/testdata/java8_debug.yaml

Fixes #467.
~~Travis build will fail to due my mistake in https://github.com/GoogleContainerTools/distroless/pull/469#issuecomment-588468371. #469 should be merged first.~~ UPDATE: resolved

Upgrade Java to 8u242 and 11.0.6 (from 8u232 and 11.0.5)

---

base/testdata/base.yaml

This is useful for reliably detecting base images, and if you like it you should put a test on it.

Add test for OS PRETTY_NAME

---

cacerts/jksutil/test_jks.sh

At some point it seems like keytool changed from outputting
the SHA1 fingerrints to SHA256 by default. To make this work with
either version, this patch changes the test to use the verbose flag
which prints both SHA1 and SHA256 fingerprints.
Fixes #492.

Update jksutil test to work with newer versions of keytool

---

package_manager/BUILD

Fixes #434 (but only after merging #477). See https://github.com/GoogleContainerTools/distroless/pull/477#issuecomment-593132767.
This shebang idea has already been suggested by others (https://github.com/GoogleContainerTools/distroless/issues/434#issuecomment-570410807 and https://github.com/GoogleContainerTools/distroless/issues/434#issuecomment-584838725).

Fix dpkg_parser.par Python3 shebang

---

cloudbuild.yaml

I forgot to update `cloudbuild.yaml` in #477.
#477 changed how we build; we should [build `dpkg_parser.par` first](https://github.com/GoogleContainerTools/distroless/pull/477/files#diff-6a3371457528722a734f3c51d9238c13R18).

Build dpkg_parser.par in cloudbuild.yaml

---

WORKSPACE

fix for https://github.com/GoogleContainerTools/distroless/issues/501

Update buster to latest security snapshot

---

WORKSPACE
java/BUILD

I switched over some builds for a project I'm involved with to use the Debian 10-based Java image and noticed that this issue: https://github.com/GoogleContainerTools/distroless/issues/321 seems to have reappeared.
After running with similar debugging flags to the original issue I managed to track it down to a missing `libuuid1` dependency under Debian 10.
This change will also add the dependency to the Debian 9-based image where it is not required but also has no effect.
I've tested this locally and with the project in question and it seems to have fixed the issue.

Adds libuuid1 to the Java distroless images.

---

package_manager/dpkg_parser.py

This patch is a retry download patch mentioned in https://github.com/GoogleContainerTools/distroless/issues/509.
But on my network/computer, distroless build is timedout. I could not test all build process.

#509: retry with range download to recover from connection close from Debian server

---

WORKSPACE

Resolves https://github.com/GoogleContainerTools/distroless/issues/225
This moves to a 64-bit busybox, keeping the version the same.
Conceptually the same as https://github.com/GoogleContainerTools/distroless/pull/380 but a much simpler implementation.

fix: switch to 64-bit busybox instead of 32-bit uclibc busybox

---

examples/rust/.dockerignore

I added .git/ and target/ folders to the .dockerignore file, it's also possible to add **/.git and **/target for recursive ignore, but it feels like it's too much intervention for the user.

Add .dockerignore

---

examples/nodejs/Dockerfile

Include dependency install in node.js example Dockerfile to make need of multistage build more clear.

Make example node.js Dockerfile more declarative

---

WORKSPACE

This includes the Debian 10.4 point release. The following Debian 10
packages were updated:
base-files       10.3+deb10u4
libgnutls30       3.6.7-4+deb10u4
libldap-2.4-2     2.4.47+dfsg-3+deb10u2
libldap-common    2.4.47+dfsg-3+deb10u2
tzdata            2020a-0+deb10u1

WORKSPACE: Update to latest Debian snapshots

---

java/testdata/java8.yaml
java/testdata/java8_debug.yaml

Commit ddaef2acc3 updated the Debian snapshots, which included a
security update to Java 8. Fix the version number in the tests.
Fixes:
//java:java8_debian9_test
//java:java8_debug_debian9_test

Fix CI: Failing Java tests due to security update

---

WORKSPACE

This updates ca-certificates to 20200601~deb10u1, which was added to
buster-updates. This may cause problems when packages are added to
buster-updates, but then updated again into the stable point releases.
For example, tzdata version 2019c-0+deb10u1 was added to
buster-updates, then later tzdata version 2020a-0+deb10u1 was added
to buster for the 10.4 "point release". Since dpkg_list takes the first
package it finds, it finds the older tzdata version.
We should eventually fix the dpkg_list function to actually attempt to
order by version numbers to resolve this. For now, I've manually pinned
the tzdata version to ensure it gets the latest version.

WORKSPACE: Add buster-updates to debian10 to update ca-certificates

---

cloudbuild.yaml

(from https://github.com/GoogleContainerTools/distroless/pull/521#issuecomment-643320096)
`cloudbuild.yaml` was not building the new Python3 non-root images introduced in #521, and that's why the images have not been published automatically. I've verified that the fixed `cloudbuild.yaml` successfully publishes to my GCP project.
```diff
bazel run --host_force_python=PY2 //experimental/python3:python3_debian9
bazel run --host_force_python=PY2 //experimental/python3:python3_debian10
+    bazel run --host_force_python=PY2 //experimental/python3:python3_nonroot_debian9
+    bazel run --host_force_python=PY2 //experimental/python3:python3_nonroot_debian10
bazel run --host_force_python=PY2 //experimental/python3:debug_debian9
bazel run --host_force_python=PY2 …
```

Fix broken cloudbuild.yaml that stalled automatic image publishing

---

cloudbuild.yaml

@evanj gcr.io/cloud-builders/bazel cached on GCB wasn't even 2.2.0, so it was already broken after #529.
And it seems like they want to deprecate `gcr.io/cloud-builders/bazel`.
```
$ docker run --rm -it gcr.io/cloud-builders/bazel
***** NOTICE *****
A supported `bazel` image, including multiple tagged versions,
is available at
http://gcr.io/cloud-marketplace-containers/google/bazel.
***** END OF NOTICE *****
```

Use supported Bazel 3.2.0 image in cloudbuild.yaml

---

package_manager/dpkg_parser.py

by replacing getheader() with get().
getheader() function is in PY2 HTTPMessage but not in PY3 HTTPMessage. It seems to me a bug in six that getheader() function is available in PY2.

fix dpkg_parser in python3

---

cloudbuild.yaml
java/BUILD
java/testdata/java_base.yaml
java/testdata/java_base_debug.yaml

This PR adds four images for java base.
These images can be used for jlink based jre as mentioned in #439 
Example Usage:
```
FROM amazoncorretto:11 as jreBuilder
RUN jlink \
--add-modules jdk.unsupported,java.sql,java.desktop,java.naming,java.management,java.instrument,java.security.jgss,java.rmi \
--verbose \
--strip-debug \
--compress 2 \
--no-header-files \
--no-man-pages \
--output /jre
FROM bazel/java:java_base_debian10
ARG JAR_FILE
COPY --from=jreBuilder /jre /usr/lib/jre
ENTRYPOINT ["/usr/lib/jre/bin/java", "-jar", "./app.jar"]
COPY ./target/${JAR_FILE} ./app.jar
```

Added base image for java. Fixes #439

---

cloudbuild.yaml
java/cloudbuild.yaml

Fixes #558.
Separates out Java image publishing from `/cloudbuild.yaml` into `/java/cloudbuild.yaml` to overcome #558. I ran these `cloudbuild.yaml` files locally to publish images to my personal GCP project and they succeeded.
Turns out the release pipeline was just a Cloud Build trigger on the Distroless GCP project. (_Cloud Build_ > _Triggers_ on Google Cloud Console (console.cloud.google.com)). I added a new trigger for `/java/cloudbuild.yaml` on GCP.
While fixing this, locally I encountered the 4000-character limit of `args:` which I hadn't seen before.
```
... : invalid .steps field: build step 1 arg 1 too long (max: 4000)
```
Not sure if it affects the actual Cloud Build release, because at least the release pipeline ran successfully last Monday. However, to be able to test this …

Use two cloudbuild.yaml files to work around Cloud Build limitation

---

cloudbuild.yaml

Fixes #566.
New tags:
- `gcr.io/distroless/base:latest`
- `gcr.io/distroless/base-debian9:latest`
- `gcr.io/distroless/base-debian10:latest`
- `gcr.io/distroless/cc:latest`
- `gcr.io/distroless/cc-debian9:latest`
- `gcr.io/distroless/cc-debian10:latest`
- `gcr.io/distroless/static:latest`
- `gcr.io/distroless/static-debian9:latest`
- `gcr.io/distroless/static-debian10:latest`
This will take effect only after removing the internal system controlling these tags.
Related: #436 #483
---
The Debian snapshot package repo has been very unstable recently, so tests are very flaky.

Publish latest tags on base, cc, and static

---

nodejs/README.md

from nodejs readme. currently returns github 404 page

Fix broken link to base image README

---

cloudbuild.yaml

A sample run of this (on my project) produced:
```
crane manifest gcr.io/mattmoor-knative/static:nonroot
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 526,
"digest": "sha256:2b4a48f7c192111b0ff59633f1ac68f0079b8e8306bf0c5cb55169241ba464c9",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 526,
"digest": "sha256:9169d04187d456913f000daeddc3fa2c2ae2e27dca5297b697d5c1d6f5b132c7",
"platform": {
"architecture": "arm64",
"os": "linux"
}
}
]
}
```
Based on: https://github.com/GoogleContainerTools/distroless/pull/586
Fixes: …

Publish static images as manifest lists.

---

cloudbuild.yaml

This should fix `Your build failed to run: generic::invalid_argument: invalid build: invalid .steps field: build step 1 arg 1 too long (max: 4000)` error from https://github.com/GoogleContainerTools/distroless/pull/612.
In this case no revert changes https://github.com/GoogleContainerTools/distroless/pull/618 will be required.

Fixed 4000-character limit error

---

cloudbuild.yaml

After adding many more architecture images and tags, sometimes the non-Java Cloud Build can take more than 30 minutes.

Increase GCB timeout by 15 minutes

---

cloudbuild.yaml
test.sh

Resolves #646.
With this change, I haven't seen a failure in the last few attempts. At least this definitely makes it robust.

Warm up amd64 debian 10 package list to avoid flakiness

---

WORKSPACE

close #662 
I've spent some time trying to test it locally, but Bazel kept failing on random errors...

chore: bump nodejs version to fix security issues

---

updateWorkspaceSnapshots.sh

The daily GitHub Actions workflow to upgrade packages started to fail at some point recently. Disabling parallel runs as we did for Cloud Build:
https://github.com/GoogleContainerTools/distroless/blob/1e4a8bb3ad03f71b572cbcb3bbc25f3fd8d0ff14/cloudbuild.yaml#L20-L33

Disable parallel runs when building package bundles when updating snapshots

---

WORKSPACE

Bump node versions to fix security issues ( https://nodejs.org/uk/blog/vulnerability/february-2021-security-releases/ ).
Tried to run tests locally with little luck, hope everything is OK.

Bump nodejs to fix security issues

---

cloudbuild.yaml
cloudbuild_cosign.sh

Right now signatures will be stored in gcr.io/distroless-signatures -- this will be switched to the main distroless repo once we are confident signing is working as expected!

Add signing step to distroless release

---

cloudbuild_cosign.sh

Signing just `gcr.io/distroless/nodejs:debug` worked! It can be verified with:
```
$ cat cosign.pub 
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWZzVzkb8A+DbgDpaJId/bOmV8n7Q
OqxYbK0Iro6GzSmOzxkn+N2AKawLyXi84WSwJQBK//psATakCgAQKkNTAA==
-----END PUBLIC KEY-----
cosign verify -key cosign.pub gcr.io/distroless/nodejs:debug
```
Now we can go ahead and sign all images

Store all signatures in distroless repo

---

WORKSPACE
experimental/busybox/BUILD

This PR is reference to #716. The `ppc64le busybox` binary currently present in the images is wrong and binary from `debian` is old hence using `ppc64le` binary provided by [docker-library/busybox](https://github.com/docker-library/busybox/blob/dist-ppc64le/stable/musl/busybox.tar.xz).
cc: @dlorenc

Add correct busybox binary for ppc64le architecture

---

WORKSPACE
checksums.bzl

Something happened with github and shas, we need to bump rules_docker again.

Update rules_docker and versions

---

cloudbuild.yaml

Fixes: https://github.com/sigstore/cosign/issues/289
+v0.4.0
v0.2.0 -> v0.3.1
We'll drop v0.3.1 eventually, but dual signing lets us support older clients for a time
Signed-off-by: Jake Sanders <jsand@google.com>

Update cosign steps

---

WORKSPACE

Previous versions of node aren't updated anymore, so those don't have any new changes.

Bump nodejs14 to v14.17.1

---

.github/workflows/ci.yaml

It seems that Travis builds haven't been running for [about a month](https://travis-ci.org/github/GoogleContainerTools/distroless/builds), since travis-ci.org was shut down.
This PR runs the same tests defined in .travis.yml in GitHub Actions, on every PR and commit to the repo.
GitHub Actions, unlike Travis, doesn't currently support arm64 runners, so there's technically still a reason we might want to migrate to travis-ci.com. But if arm64 builds aren't necessary, we could transition entirely to GitHub Actions.

Run CI tests in GitHub Actions

---

WORKSPACE

The [last `rules_docker` dep update](https://github.com/GoogleContainerTools/distroless/pull/728) was to avoid an issue where a transitive dependency resulted in inconsistent GitHub archive downloads and mismatched SHAs when depending on them in Bazel (more info https://github.com/kubernetes/kubernetes/issues/99376).
This change has since been incorporated in a real `rules_docker` release, [v0.17.0](https://github.com/bazelbuild/rules_docker/releases/tag/v0.17.0), which this PR updates to. Depending on a real release seems safer than depending on some random commit in the rules_docker repo.
v0.17.0 currently points to https://github.com/bazelbuild/rules_docker/commit/881e779b5c5b2fad2eeda7ed1f5cb9cbfc10fcdb

Update rules_docker dep to v0.17.0

---

README.md

[`gcr.io/distroless/java/jetty-debian10`](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java/jetty-debian10?gcrImageListsize=30) doesn't exist, and the link to java/jetty/README.md is a 404.

Remove bad link for jetty image

---

README.md

Compare distroless/static sizes to alpine and debian, as well as a moderately sized jpeg, and https://github.com/GoogleContainerTools/distroless.

Add size comparisons to README.md

---

WORKSPACE
checksums.bzl
package_manager/README.md
package_manager/dpkg.bzl
package_manager/dpkg_parser.py
package_manager/parse_metadata.py
updateWorkspaceSnapshots.sh

Add support for Packages.xz
- Also update workspace to use Packages.xz instead of Packages.gz
- Users may chose to still use Packages.gz if they want if expliclty specify packages_url
- this is a breaking change to dpkg_src rule
- rename input: packages_gz_url -> packages_url
- when using snapshots will only look for Packages.xz, the sha256 must reference
a Packages.xz, it will not use the Packages.gz.

Add support for Packages.xz

---

BUILD
WORKSPACE
base/BUILD
base/distro.bzl
base/testdata/debian11.yaml
checksums.bzl
cloudbuild.yaml
package_bundle_amd64_debian11.versions
package_bundle_arm64_debian11.versions
package_bundle_arm_debian11.versions
package_bundle_ppc64le_debian11.versions
package_bundle_s390x_debian11.versions
package_manager/util.py
updateWorkspaceSnapshots.sh

Adds images for:
static-debian11:latest-amd64
static-debian11:nonroot-amd64
static-debian11:debug-amd64
static-debian11:debug-nonroot-amd64
static-debian11:latest-arm64
static-debian11:nonroot-arm64
static-debian11:debug-arm64
static-debian11:debug-nonroot-arm64
static-debian11:latest-arm
static-debian11:nonroot-arm
static-debian11:debug-arm
static-debian11:debug-nonroot-arm
static-debian11:latest-s390x
static-debian11:nonroot-s390x
static-debian11:debug-s390x
static-debian11:debug-nonroot-s390x
static-debian11:latest-ppc64le
static-debian11:nonroot-ppc64le
static-debian11:debug-ppc64le
static-debian11:debug-nonroot-ppc64le
base-debian11:latest-amd64
base-debian11:nonroot-amd64
base-debian11:debug-amd64
base-debian11:debug-nonroot-amd64
base-debian11:latest-arm64 …

Preliminary debian11 (bullseye) support

---

package_manager/BUILD

The dpkg_parser.py file imports the lzma system package, which only
exists in Python 3. On my system (Debian 10), the default "python"
is still Python 2. As a result, the built dpkg_parser.par does not
execute. Update the interpreter to use "python3" explicitly.
The python_version attribute does nothing at the moment, but it seems
to me that is likely a bug in the subpar bazel rules. Let's set it
since that seems to be the documented way to change the Python
version for a py_binary.

package_manager dpkg_parser: Use /usr/bin/env python3

---

experimental/python2.7/testdata/debian9.yaml
experimental/python3/testdata/debian9.yaml

This test configuration is no longer used now that Debian 9 is no
longer supported.

python2.7/python3: rm testdata/debian9.yaml

---

WORKSPACE
cc/BUILD

This has not been carefully tested, but //examples/cc does work.
This is necessary for Python images.

cc: Add debian11 support

---

examples/cc/BUILD
examples/cc/hello.c
examples/cc/hello_cc.cc
examples/cc/testdata/hello.yaml
examples/cc/testdata/hello_cc.yaml

While this example is nearly identical to the existing C program,
this serves as a test to make sure the //cc image contains the
right shared libraries for C++ programs. The exact libraries are
changing with the Debian 11 release, so this helped verify that
change.

examples/cc: Add C++ example program

---

cloudbuild.yaml
cloudbuild_cosign.sh
cloudbuild_jq.sh

Instead of hardcoding the images to sign, read all the images that were built from the manifest and sign them -- no images should be left behind now! 
I tried on my own project and this worked! There were 241 images to sign 😮 
fixes https://github.com/GoogleContainerTools/distroless/issues/803

Make sure we are signing every image built

---

cloudbuild.yaml

The bump to 1.1 accidentally picked up a change that removed a shell.
This image puts the shell back, fixing the signing here.
Signed-off-by: Dan Lorenc <dlorenc@google.com>

Bump cosign to the latest CI image.

---

cloudbuild.yaml
cloudbuild_cosign.sh

This refactors the cosign script for distroless, so that the arguments are passed through from `cloudbuild.yaml`, and shifts where `-key ...` is passed to be in `cloudbuild.yaml`.
This is preparation to start *also* signing the distroless images with a "keyless" flow, once https://github.com/sigstore/cosign/pull/652 lands and cosign 1.2 cuts.

Refactor the cosign script.

---

WORKSPACE
java/BUILD

I'm experiencing the issue #729 .  
This change will add the libharfbuzz0b and dependencies related to Debian 10-based Java image.
I've tested this locally and it seems to have fixed the issue.

Add libharfbuzz0b to java image

---

cloudbuild.yaml
provenance/provenance-task.yaml

Adds a task which:
1. pulls in the distroless repo at the specified commit
2. builds the images and pushes to an insecure registry to the cluster
3. gets the digests for six distroless images, and saves them in the IMAGES result
This six images will be picked up by Tekton Chains to generate provenance
If this works, we can definitely add in more images. we can probably have up to 30 per Task before we hit the maximum size for Tekton results.

Add Tekton task for generating provenance 

---

cloudbuild.yaml
cloudbuild_cosign.sh

User defined env vars have to [start with an underscore](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values) and need to be specified on the trigger itself, so I updated the trigger with the value for `_KMS_VAL` and `_TKN_VERSION`
`cloudbuild_cosign.sh` also wasn't being run because the wrong shell was specified 
Builds have been broken since #823, hopefully this should fix it (cc @mattmoor )

Fix user-defined substitutions and shell for cloudbuild_cosign script

---

gcscache/cmd/sync.go
gcscache/internal/dpkg/parser.go

Handle scanner errors and use bytes instead of relying on the built in readers on byte buffer

Fix readers

---

BUILD
nodejs/BUILD
nodejs/testdata/check_certificate.js
nodejs/testdata/check_certificate.yaml
nodejs/testdata/nodejs12.yaml
nodejs/testdata/nodejs14.yaml
nodejs/testdata/nodejs16.yaml

def: debian 11 support #844 
- Add debian11 variants
- Does not change default to point at debian11
- Add test for nodejs images

Add nodejs debian11 support

---

cloudbuild.yaml

We recently had a build fail at the 45 min mark in the middle of step 4 -- signing with a GCB service account. The builds that pass are taking around 40 minutes. Increasing to 60m should be enough for all builds to pass.

Increase cloudbuild timeout to 60m

---

.github/workflows/ci.yaml
BUILD
WORKSPACE
checksums.bzl
java/BUILD
java/jre_ver.bzl
java/testdata/java17_debian11.yaml
java/testdata/java17_debug_debian11.yaml
java/testdata/java17_nonroot_debian11_certs.yaml
java/testdata/java17_nonroot_debian11_encoding.yaml
java/testdata/java17_nonroot_debian11_libharfbuzz.yaml
java/testdata/java17_root_debian11_certs.yaml
java/testdata/java17_root_debian11_encoding.yaml
java/testdata/java17_root_debian11_libharfbuzz.yaml
package_bundle_amd64_debian11.versions
package_bundle_arm64_debian11.versions
package_bundle_arm_debian11.versions
package_bundle_ppc64le_debian11.versions
package_bundle_s390x_debian11.versions

- Fundamentally the only difference between the 11 and 17 dependencies
is libatomic1 which is not available for amd64 anyway
- https://packages.debian.org/bullseye/openjdk-17-jre-headless
- https://packages.debian.org/bullseye/openjdk-11-jre-headless

Add java17 (not published)

---

examples/go/Dockerfile
examples/go/main_test.go

This pull request suggests the following changes:
* Update to golang:latest 
* Addition to initialize the module, needed for compilation
* Disable of cgo as the example does not require it
* Default to Distroless static vs base
* Documentation guidance on when it is necessary to utilize larger distroless/base base image

update to use distroless static vs base, including qualified guidance

---

provenance/build-distroless-task.yaml

Most recent task from two days ago timed out at 1 hour, doubling.

Increase timeout on bazel task for provenance generation

---

BUILD
cloudbuild_cosign.sh
cloudbuild_docker.sh

- new java 17 images
- java on debian 11 in now multi arch (amd64, arm64)
- multiarch manifests are signed by cosign for (base, 17, 11)
- new naming
- new tagging strategy is `java(variant)-debian(version):...` or
`java(-base,11,17)-debian(10,11):(latest,nonroot,debug,debug-nonroot)`
this provides some standardization around the tagging
- old tags exists for now, but will be removed after notifying users

Publish more java images

---

cloudbuild.yaml
cloudbuild_cosign.sh

create a world writeable tmp dir in workspace so cosign (nonroot)
container has a place to work
this is the second attempt at fixing #914

Fix cosign build

---

README.md

Based on the following file, I believe that `debug` should be added as a prefix rather than as a suffix.
https://github.com/GoogleContainerTools/distroless/blob/b19f550dce74b65e09706e46fc82c0075434f563/BUILD#L29

Update README.md - fix debug tags

---

java/BUILD

Include libcrypt1 in debian11 java images (fix netty-tcnative)

---

BUILD
cloudbuild_cosign.sh
cloudbuild_docker.sh

This converts the :16 tags to be multi-arch based on separate -amd64 and -arm64 tags. This ensures consumers can actually pin to a supported version and take advantage of multi-arch.
Most tags are now constructed systematically, which ensures they can't be missed while manually constructing the image list. This includes :latest and :debug tags.
debian10 is not getting multi-arch images like before.
Fixes #878.

Add multi-arch to node version tags

---

busybox_archives.bzl
experimental/busybox/BUILD

This PR is reference to https://github.com/GoogleContainerTools/distroless/issues/657. The armv8l busybox binary currently present in the images doesn't work on arm64 CPUs without arm32 support hence using arm64v8 binary provided by [docker-library/busybox](https://github.com/docker-library/busybox/blob/dist-arm64v8/stable/musl/busybox.tar.xz).
This solution is inspired by the one for ppc64le arch: https://github.com/GoogleContainerTools/distroless/pull/723
I confirm the debug arm64 image built form this PR works well on Ubuntu 21 arm64 in Parallel Desktop and Docker on Apple Macbook Air 2020 (M1). This this  my build for try:
```
docker run -it mrmyh/base:debug-arm64
```

Add correct busybox binary for arm64 architecture

---

.github/workflows/update-deb-package-snapshots.yml

Appears to me that cron jobs are run in the context of a user that last changed the cron config (me). So commits are also made under that "actor". Just change the author here for the commits for consistency on the PRs.

Update author to bot on deb updater

---

cloudbuild.yaml

update cosign image to use release v1.6.0
xref: https://github.com/GoogleContainerTools/distroless/issues/966#issuecomment-1051290681
cc @imjasonh @mattmoor

update cosign image to use release v1.6.0

---

base/testdata/debug.yaml
busybox_archives.bzl
experimental/busybox/BUILD

Fix issue https://github.com/GoogleContainerTools/distroless/issues/1014, just for amd64 platform
Signed-off-by: Jin Tang Cheng <jtcheng@cn.ibm.com>

upgrade busybox to avoid security vulnerabilities

---

node_archives.bzl
nodejs/BUILD
nodejs/README.md
nodejs/testdata/nodejs18.yaml

Unsure wether to add it now, or when Active LTS starts in October.

Add node18 `18.0.0`

---

README.md
examples/go/Dockerfile
examples/go/go.mod

I think `go mod download` is better suited for an example rather than `go get -d -v` as everyone should be using modules at this point.
Also consolidated the example and the one shown in the README as well as bumping to Go 1.18

Update example for Go 1.18 and switch to using `go mod download`

---

RELEASES.md

This PR fixes a relative link to the top-level `cloudbuild.yaml` in  in `RELEASES.md`.

Fix relative link to cloudbuild.yaml in RELEASES.md

---

.github/workflows/ci-cache.yaml
debian_package_manager/internal/build/build.go
debian_package_manager/internal/deb/packageindex.go
debian_package_manager/internal/deb/snapshot.go

- They don't seem to be published anymore
- We will probably see some regressions in versions
for those architectures unfortunately
- Better to not keep the rest of distroless hostage
on this
fixes #1100

Ignore s390x and ppc64le security indexes debian10

---

.github/workflows/scorecards-analysis.yml

This PR fixes:
- Add `id-token: write` needed for `publish_results: true`
- Update to latest `v2.0.3` version which includes a bug fix.

🐛 Fix failing Scorecard runs

---

BUILD
base/base.bzl

will be published to `gcr.io/distroless/preview/base-nossl*` and moved to `gcr.io/distroless/base-nossl*` when tested
part of #1098

Add base_nossl image

---

SUPPORT_POLICY.md

I found the current version of the table a little non-informative.
Looking at the previous version, I got to understand how it is supposed to work.

Fix Debian version in support policy table

---

.github/workflows/ci.yaml

fixes issue with ci glibc incompatibility
reduces duplicationin build and test

Use ubuntu 20.04 for tests, separate out tests

---

base/base.bzl
cc/BUILD
cloudbuild.yaml
experimental/python3/BUILD
java/BUILD
nodejs/BUILD

:bug: This uses `SOURCE_DATE_EPOCH` so that instead of the Unix epoch, distroless images use the timestamp of the git commit from which they are built.
/kind bug

Fix: Use `SOURCE_DATE_EPOCH` for the distroless images.

---

base/base.bzl
cc/BUILD
cloudbuild.yaml
experimental/python3/BUILD
java/BUILD
nodejs/BUILD

Reverts GoogleContainerTools/distroless#1203
Stamping was causing some unnecessary updates in repos: #1239 . We'll revert this for now and figure out a better solution.

Revert "Fix: Use `SOURCE_DATE_EPOCH` for the distroless images."

---

node_archives.bzl
nodejs/testdata/nodejs18.yaml

This version fixes a bug included in v18.14.1 (https://github.com/nodejs/undici/issues/1935)
release note: https://nodejs.org/en/blog/release/v18.14.2/

bump nodejs18 to v18.14.2

---

BUILD
README.md
SUPPORT_POLICY.md
node_archives.bzl
nodejs/BUILD
nodejs/README.md
nodejs/testdata/nodejs20.yaml

https://nodejs.org/en/blog/release/v20.0.0

Add nodejs20

---

BUILD
README.md
SUPPORT_POLICY.md
node_archives.bzl
nodejs/BUILD
nodejs/README.md
nodejs/testdata/nodejs14.yaml

This **_must_** be merged after the actual EOL date (30 Apr 2023)
Indirectly this PR closes https://github.com/GoogleContainerTools/distroless/issues/1002

Remove EOL nodejs14

---

base/testdata/debug.yaml
busybox_archives.bzl

This is an update to busybox to [1.35.0](https://github.com/docker-library/official-images/blob/master/library/busybox). 
I was hoping to upgrade it to `1.36.0` or higher to get rid of this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2022-28391) but unfortunately that is still marked as `unstable` in the docker-library tag list so seems "unwise".  `1.35.0` also matches alpine's currently used version
Busybox themselves [seems to have marked their last stable release as 1.34.1](https://busybox.net/news.html) in 2021 so it's possible I'm mistaken here and we want to for stability sake leave this as `1.34.1` and close this mr.

Updating busybox to 1.35.0

---

node_archives.bzl
nodejs/testdata/nodejs16.yaml
nodejs/testdata/nodejs18.yaml
nodejs/testdata/nodejs20.yaml

This fixes some vulnerabilities which including 3 high severity and 7 medium severity for the 20.x, 18.x, and 16.x release of nodejs.
more information: https://nodejs.org/en/blog/vulnerability/june-2023-security-releases

June 20 2023 Security Releases for 20.x, 18.x and 16.x of nodejs

---

RELEASES.md

cloudbuild.yaml is inside .cloudbuild directory

[Docs] Fix relative link for Cloudbuild.yaml

---

WORKSPACE

Fixes #1381
[rules_go](https://github.com/bazelbuild/rules_go) is broken for the ppc64le arch since version v0.36.0 which introduced [this change](https://github.com/bazelbuild/rules_go/pull/3336).
Until https://github.com/bazelbuild/rules_go/issues/3531 is resolved a good workaround is to revert to v0.35.0.

Revert io_bazel_rules_go to v0.35.0

---

BUILD
README.md
SUPPORT_POLICY.md
examples/nodejs/BUILD
node_archives.bzl
nodejs/BUILD
nodejs/README.md
nodejs/testdata/nodejs16.yaml

It reaches EOL on monday ([2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol)), and is no longer supported.

Drop node16

---

BUILD
CONTRIBUTING.md
examples/nodejs/BUILD
nodejs/BUILD

This pull request adds Node.js (v18, v20) language support for Debian 12 (bookworm).
References #1398.

feat: Add Node.js support for Debian 12

---

private/remote/node_archive.bzl

This is messing with scanners. Instead keep writing sboms and suggest to users of scanners to use a scanner that is aware of nodejs binary releases.
deals with #1373

Disable writing control info for node archives

---

README.md

Teleport uses Distroless since Teleport 13 for its recommended images.
https://goteleport.com/docs/changelog/#helm-chart-uses-distroless-based-container-image-by-default

Add Teleport as a Distroless user

---

node_archives.bzl
nodejs/testdata/nodejs18.yaml
nodejs/testdata/nodejs20.yaml

Security fixes part of https://nodejs.org/en/blog/vulnerability/october-2023-security-releases

Bump `nodejs18` to `18.18.2` and `nodejs20` to `20.8.1`

---

README.md
SUPPORT_POLICY.md
examples/python3/BUILD

resolves #1409 to note that Python on Debian 12 is out of experimental while it is still built for Debian 11 from experimental. Another PR would need to move all of Python builds out of experimental.
Update:
* README
* Support Policy
* Examples
I am focusing on the Debian 12 Python topic, the Debian 11 Python is still in the experimental builds.

resolves #1409 to note that Python on Debian 12 is out of experimental

---

debian_package_manager/internal/deb/snapshot.go
debian_package_manager/internal/deb/snapshots_test.go

Look back an actual day instead of one snapshot, as there could be many snapshots from a single day and all of those could still be sync'ing.
Hopefully this helps with snapshot consumption. Also fixes the issue from #1325

Make lookback date more robust

---

nodejs/README.md

doc: fix node js release url

---

java/BUILD
java/testdata/java21_debian12.yaml
java/testdata/java21_debug_debian12.yaml
private/remote/temurin_archive.bzl

- put temurin ca certs in debian common area and link temurin install ca certs to that, this provides some continuity if people want to install their own roots
- create intermediate base that is shared by java-base and java21, this allows us to remove libharfbuzz and deb-cacerts from the java21 install

java21 improvements

---

.pre-commit-config.yaml

This should prevent CI failures related to formatting beforehand therefore shortening the dev roundtrip for formatting failures.

chore: introduce precommit

---

java/testdata/java21_debian12.yaml
private/remote/temurin_archive.bzl

In the future we should use a tar rule that preserves file permissions, this approach is a bit brittle
ref: https://github.com/GoogleContainerTools/distroless/issues/1405#issuecomment-1841898382

Make jexec and jspawnhelper executable

---

node_archives.bzl
nodejs/testdata/nodejs18.yaml
nodejs/testdata/nodejs20.yaml

This fixes some vulnerabilities which including 4 high severity issues, 4 medium severity issues and 1 low severity issue for the 20.x and 18.x release of nodejs.
more information: https://nodejs.org/en/blog/vulnerability/february-2024-security-releases

February 14 2024 Security Releases for 20.x and 18.x of nodejs

---

examples/rust/BUILD
examples/rust/Dockerfile

Current rust builds want newer glibc only present in debian12, else CMD errors in runtime.
distroless/cc: README: Any other tags are considered deprecated and are no longer updated → use distroless/cc-debian12
build-env: lessen cargo pin to only major version. There is no practical need for it to be pinned to patch.

Update rust example

---

CONTRIBUTING.md
WORKSPACE
base/base.bzl
cc/BUILD
examples/cc/BUILD
examples/go/BUILD
examples/java/BUILD
examples/nodejs/BUILD
examples/nonroot/BUILD
examples/python3/BUILD
experimental/python3/BUILD
java/BUILD
java/jetty/BUILD
nodejs/BUILD
private/oci/cc_image.bzl
private/oci/go_image.bzl
private/oci/java_image.bzl
private/oci/rust_image.bzl
private/oci/sign_and_push.bzl
private/pkg/test/oci_image/BUILD.bazel
python3/BUILD

Upgrading rules_oci to get https://github.com/bazel-contrib/rules_oci/pull/335 into distroless. 
Changes
- reorder some of load statements
- bring in container_structure_test as rules_oci no longer provides it builtin
- upgrade rules_oci

chore: upgrade rules_oci

---

java/testdata/java21_debian12.yaml
java/testdata/java21_debug_debian12.yaml
java_archives.bzl

In our organisations we're getting warnings about CVEs in Java 21.0.1, f.ex https://nvd.nist.gov/vuln/detail/CVE-2024-20952. These should be fixed in 21.0.2.

chore: update java 21 patch version

---

WORKSPACE
base/base.bzl
busybox_archives.bzl
experimental/busybox/BUILD
experimental/busybox/commands.bzl

With https://github.com/GoogleContainerTools/distroless/pull/1538 i have discovered that busybox archives are non-reproducible.  
Its uid/gid mtime and permissions are directly affected by Bazel and the Host.

fix: make busybox reproducible

---

WORKSPACE

Updates the main to use `v0.2.1`,  Diff report due to changes in java_keystore in https://github.com/GoogleContainerTools/rules_distroless/pull/25 is expected but it should be harmless 
Prefactor for https://github.com/GoogleContainerTools/distroless/pull/1542

chore: update rules_distroless

---

node_archives.bzl
nodejs/testdata/nodejs18.yaml
nodejs/testdata/nodejs20.yaml

This fixes some vulnerabilities which including 1 high severity issue and 1 medium severity issue for the 20.x and 18.x release of nodejs.
more information: https://nodejs.org/en/blog/vulnerability/april-2024-security-releases

April 3, 2024 Security Releases for 20.x and 18.x of nodejs

---

knife

This fixes a bug where date calls made from update-snapshots were assuming bsd date and gnu date is the same.

fix: use gnu date instead

---

.github/workflows/update-deb-package-snapshots.yml
knife

Replaces gsed with sed, which is gnu sed in linux by default. I missed this as i was writing this script on macos.

fix: gsed is available as sed on linux

---

node_archives.bzl
nodejs/testdata/nodejs18.yaml
nodejs/testdata/nodejs20.yaml

This fixes a vulnerability which including 1 high severity issue for the 20.x and 18.x release of nodejs.
more information: https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

April 10, 2024 Security Releases for 20.x and 18.x of nodejs

---

knife

We don't really use this stuff anymore (and haven't in years). Python code was used for the old old apt stuff

remove python formatting and checks

---

BUILD

This should make any image without an explicit debian version now just point to debian12 (instead of debian11) images.

Make debian12 the default image

---

knife

we were `head`ing instead of `tail`ing, also made a few other changes while I was in there.
fixes #1577

Update knife to pick the latest snapshot closest to "yesterday"

---

node_archives.bzl
nodejs/testdata/nodejs20.yaml

Just a fix for Windows https://nodejs.org/en/blog/release/v20.13.1, but update it nonetheless.

Bump `nodejs20` to `20.13.1`

---

python3/README.md

This PR is a very small fix about README.
I found a broken link in README in python3 directory, and I fix it.

Fix broken link in python3 README

---

.github/workflows/update-temurin-packages.yml

We'll have to make an edit to this post-merge with distroless-bot so that group receives errors for it.

Add temurin archive updater action

---

examples/python3-requirements/Dockerfile
examples/python3-requirements/psutil_example.py

I have seen that the python3-requirements example still uses debian 11 which I have upgraded to debian 12.
I also replaced the `.format` with a fstring.

Update python3-requirements examble to debian12 and use fstring in Python Code

---

.cloudbuild/release.sh

looks like the default apt repo doesn't have every single version of bazel on tap.

use bazelisk on cloudbuild

---

BUILD

This should help people move backwards in time if we break something. People still need to track against commits we make here.

Add commit sha to all tags

---

.github/workflows/ci.yaml
.github/workflows/image-check.yaml

we don't use debian 11 anymore, so we don't need the glibc compat that 20.04 provided.

update large runners to 22.04

---

common/BUILD.bazel

fix https://github.com/GoogleContainerTools/distroless/issues/1661

fix: the ownership of /home should be 0:0

---

MODULE.bazel.lock
nodejs/testdata/nodejs18.yaml
nodejs/testdata/nodejs20.yaml
nodejs/testdata/nodejs22.yaml
private/extensions/node.bzl

https://nodejs.org/en/blog/vulnerability/january-2025-security-releases

Bump `nodejs18`, `nodejs20` and `nodejs22`

---

README.md

The link to the "Support Policy" page did not work
- use a plain relative link like the other in-repo links in this README
- also fix markdown semantics with the last heading
- should be an `h2` since there can only be one `h1` per page and that's already the first heading of the README

docs: fix broken link to "Support Policy" page

---

README.md

Several code blocks in the README were missing language specifiers
- add syntax highlighting to all code blocks
- mainly `sh` and `dockerfile`
- plus some small grammar fixes
- missing colon before a code block
- incorrect article ("an shell" -> "a shell")
- etc

docs: add syntax highlighting to various code blocks

---

MODULE.bazel.lock
nodejs/testdata/nodejs18.yaml
private/extensions/node.bzl

https://nodejs.org/en/blog/release/v18.20.7

Bump `nodejs18` to `18.20.7`

---

private/oci/sign_and_push.bzl

gcr.io/distroless/(cc|cc-debian12):<tag>
since bazel doesn't allow dicts of dicts of lists in attrs this looks a bit crazy

Fix dedup logic to handle different repos from the same image

---

BUILD
MODULE.bazel
MODULE.bazel.lock
README.md
SUPPORT_POLICY.md
examples/nodejs/BUILD
examples/nodejs/Dockerfile
examples/nodejs/node-express/Dockerfile
nodejs/BUILD
nodejs/README.md
nodejs/testdata/nodejs18.yaml
private/extensions/node.bzl

Nodejs 18 was deprecated today, and can be removed.

Deprecate node18

---

BUILD
MODULE.bazel
MODULE.bazel.lock
README.md
SUPPORT_POLICY.md
nodejs/BUILD
nodejs/README.md
nodejs/node_arch.bzl
nodejs/testdata/nodejs24.yaml
private/extensions/node.bzl

Nodejs 24 was released on Tuesday, and is the next LTS version

Add node24

---

PACKAGE_METADATA.md

Initial creation of package metadata file which will contain information about the structure of the files within Distroless images.
This PR closes https://github.com/GoogleContainerTools/distroless/issues/1809

Create PACKAGE_METADATA.md to help define the Distroless internal structures

---

.github/workflows/buildifier.yaml
.github/workflows/image-check.yaml

The new `github.com/google/go-containerregistry/cmd/crane` is requiring [Go version 1.24](https://github.com/google/go-containerregistry/blob/59a4b85930392a30c39462519adc8a2026d47181/go.mod#L3). Let's upgrade all Go versions in workflows to latest (1.25)
This will also fix the CI in https://github.com/GoogleContainerTools/distroless/pull/1861

Bump go to 1.25 in image-check and buildifier workflows

---

nodejs/BUILD

Node.js versions build variable typo
Fixes #1877

typo: nodejs versions build var

---

BUILD
README.md
private/repos/deb/deb.MODULE.bazel

Also mention they are in preview in README

Add builds for debian13 static, base, base-nossl
