WORKSPACE

Add sha256 to deb http_files

---

README.md

Add travis status badge to readme

---

examples/BUILD
examples/main.go

Add an example. Once this is in we can add more and add some docs as well.

Add a go example.

---

cloudbuild.yaml

Fixes https://github.com/GoogleCloudPlatform/distroless/issues/19

Add a cloudbuild.yaml to push images to GCR when changes are merged.

---

.travis.yml
WORKSPACE
base/BUILD
base/test.sh
base/testdata/base.yaml
java/BUILD
java/examples/BUILD
java/examples/testdata/hello.yaml
java/testdata/java.yaml

This is a companion PR to https://github.com/GoogleCloudPlatform/runtimes-common/pull/180
This won't work until that is merged and I include the workspace changes, but I've tested this locally using local_repository.

Add structure tests for our images.

---

WORKSPACE
base/BUILD
base/testdata/base.yaml
base/testdata/certs.yaml
base/testdata/check_certs.go
buildifier.sh
cacerts/BUILD
cacerts/cacerts.bzl
cacerts/extract.sh

Add ca-certificates to our base image.

---

WORKSPACE

Add a jetty sha

---

README.md
RELEASES.md
base/README.md
cc/README.md
java/README.md
python2.7/README.md

See this staged here: https://github.com/dlorenc/distroless/tree/readme#this-repository-contains-source-code-used-to-build-distroless-docker-images

Add the start of a README.

---

WORKSPACE
busybox/BUILD
busybox/testdata/debug.yaml

Something got screwed up during my rebase of #22, this should replace it.

Add a busybox-based debug container.

---

WORKSPACE

Update runtimes-common to pick up a bug fix in structure_test.

---

WORKSPACE

Update rules_docker to fix #56

Update rules_docker to pick up work around for argparse bug

---

README.md

The talk page has very limited information...

Add recording of distroless talk to README

---

.travis.yml
examples/python2.7/hello.py
package_manager/parse_metadata_test.py

Add pylint to travis, fix warnings

---

WORKSPACE
base/BUILD
base/testdata/base.yaml

Add the netbase package for /etc/services.

---

examples/python2.7/hello.py

I know that this is a Python 2 example but it no longer makes sense to write new Python code without print() as a function.

print() as a function in modern Python code

---

WORKSPACE
base/BUILD
base/testdata/base.yaml

Add packae tzdata to distroless/base.

---

WORKSPACE
base/BUILD
examples/go/BUILD
examples/java/BUILD
examples/java/testdata/hello.yaml
examples/nonroot/BUILD
examples/python2.7/BUILD

The latest update restructures the repo a bit, so a bunch of load paths change.

Upgrade to the latest rules_docker.

---

WORKSPACE

Update nodejs to version 8

---

WORKSPACE
base/BUILD
dotnet/BUILD
dotnet/README.md
package_manager/README.md
python2.7/testdata/python27.yaml
python3/BUILD
python3/testdata/python3.yaml

Among other things, this upgrades the python version in the python images, and the versions of various dependent packages.

Upgrade to debian stretch for the base image

---

WORKSPACE
python2.7/BUILD
python2.7/testdata/python27.yaml

This follows the approach of #138. It fixes #120.

Add import tests for the py2.7 stdlib

---

README.md
dotnet/README.md

Add docs describing how to use ```gcr.io/distroless/dotnet``` image.

Add dotnet gcr docs

---

WORKSPACE

Update to latest snapshot.

---

print-workspace-status.sh

Add a project default in case gcloud is not installed.

---

README.md
examples/dotnet/Dockerfile
examples/go/Dockerfile
examples/java/Dockerfile
examples/nodejs/Dockerfile
examples/python2.7/Dockerfile
examples/python3/Dockerfile

Add dockerfile example builds 
I placed the dockerfiles under the various language sets since the code exists there already

add Dockerfile examples

---

.bazelrc
examples/nonroot/testdata/user.go

This uses go cross compilation to build binaries for linux.
I also had to rewrite the passwd test to avoid using user.Current, since it requires cgo.

Make bazel * //... work.

---

WORKSPACE
base/BUILD
examples/dotnet/BUILD
examples/java/BUILD
examples/nonroot/BUILD
python3/BUILD

also added a group file with the root group, some packages expect it to exist

Update rules_docker to 0.4.0

---

WORKSPACE
base/BUILD
base/testdata/base.yaml
buildifier.sh

Add passwd_tar instead of passwd_file

---

README.md

Add link to Jib

---

experimental/dotnet/README.md
experimental/nodejs/README.md
experimental/python2.7/README.md
experimental/python3/README.md

Address some broken links and correct them for display on Github.

Correct links in documentation #216

---

WORKSPACE

Last(?) Carbon LTS before we get NodeJS 10

Upgrade NodeJS to the latest Carbon LTS

---

WORKSPACE

Update java/jetty to 9.4.14.v20181114

---

java/BUILD
java/testdata/CheckCerts.java
java/testdata/java8.yaml
java/testdata/java8_certs.yaml
java/testdata/java8_debug.yaml

Fixes #281.
Also added and enhanced existing tests.

Fix and enhance Java image tests

---

cloudbuild.yaml

Add the missing cloudbuild.yaml tag step.

---

cloudbuild.yaml

Forgot to add them to the image list at the end in #307.

Actually publish Jetty Java 11 images

---

base/BUILD
base/testdata/base.yaml

Add a 'nobody' user and group

---

WORKSPACE
java/testdata/java11.yaml
java/testdata/java11_debug.yaml

Update to snapshot from 2019-05-10 to pick up OpenJDK 11.0.3

---

CONTRIBUTING.md

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

Update URLs for Google CLA

---

BUILD
base/BUILD
base/testdata/base.yaml
cloudbuild.yaml

Fixes: #235
@mattmoor @dlorenc @jonjohnsonjr I don't have opinions about how things are tagged. Let me know and I can wrap this up

Create non-root images

---

base/BUILD

Use numeric user

---

WORKSPACE
base/BUILD
cc/BUILD
experimental/python3/BUILD

This prototypes adding Debian 10 support for the following images:
//base:base-debian10
//cc:cc-debian10
//experimental/python3:python3-debian10
This is not complete.

Experimental Debian 10 support

---

README.md

Knee jerk idea around the concern about CVEs and patching.

doc around question from #347

---

WORKSPACE
java/testdata/java11.yaml
java/testdata/java11_debug.yaml
java/testdata/java8.yaml
java/testdata/java8_debug.yaml

Upgrade Java and Jetty

---

README.md

If we are going to host discussion there, we might as well publicize
it a bit more widely.

README.md: Link to Google group, slack

---

WORKSPACE
base/testdata/debug.yaml

Fixes #225. Tested and working.

Upgrade BusyBox to 1.31.0

---

BUILD.jetty

Remove demo apps from Jetty

---

examples/dotnet/BUILD
examples/go/BUILD
examples/java/BUILD
examples/nodejs/BUILD
examples/nonroot/BUILD
examples/python2.7/BUILD
examples/python3/BUILD

Add public notice about repository code changes

---

cloudbuild.yaml

Much more efficient and better readability.

Clean up cloudbuild.yaml

---

examples/python3-requirements/requirements.txt

Addressing security dependabot

---

cloudbuild.yaml
java/cloudbuild.yaml

Talking to @ImJasonH this is the recommendation from the GCB team, see:
https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#docker

Switch to docker builder

---

WORKSPACE
checksums.bzl
updateWorkspaceSnapshots.sh

This is based on: https://github.com/GoogleContainerTools/distroless/pull/587 (this is just the final commit)
Fixes: https://github.com/GoogleContainerTools/distroless/issues/585

Generate checksums.bzl

---

base/base.bzl
base/distro.bzl
cacerts/BUILD
cloudbuild.yaml
locale/BUILD

Related: https://github.com/GoogleContainerTools/distroless/issues/583

Add arm64 variants for distroless static

---

WORKSPACE
examples/dotnet/testdata/hello_core_aspnet_debian10.yaml
examples/dotnet/testdata/hello_core_runtime_debian10.yaml
examples/dotnet/testdata/hello_core_sdk_debian10.yaml

Update to dotnet core 3.1.8 security release.
https://dotnet.microsoft.com/download/dotnet-core/3.1
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.8/3.1.8.md

feature: dotnet core 3.1.8

---

.github/workflows/update-deb-package-snapshots.yml

Ran into the same issue in https://github.com/peter-evans/create-pull-request/issues/632. Upgrading to v3 should fix it.

Upgrade "Create Pull Request" to v3

---

cloudbuild.yaml
test.sh

#647 definitely worked, but looks like we need to do the same for all bundles.
Resolves #646.

Build all package bundles individually

---

checksums.bzl
package_bundle_amd64_debian10.versions
package_bundle_arm64_debian10.versions
package_bundle_arm_debian10.versions
package_bundle_ppc64le_debian10.versions
package_bundle_s390x_debian10.versions

The cron seems to be failing still.

Bump versions, a few updates.

---

checksums.bzl
package_manager/dpkg_parser.py
updateWorkspaceSnapshots.sh

I don't like it, but I also do. This is much less flaky.
Signed-off-by: Dan Lorenc <dlorenc@google.com>

Switch to curl for downloads.

---

BUILD
cloudbuild.yaml
cloudbuild_cosign.sh
cloudbuild_docker.sh
updateWorkspaceSnapshots.sh

It's been EOL for almost a year already.

Stop updating most debian9 images.

---

BUILD
base/base.bzl
cloudbuild_docker.sh

Closes #571 .
Necessary to close https://github.com/bazelbuild/rules_docker/issues/1642

Adding static_debug variant of the base image.

---

BUILD

Try reenabling java builds.

---

cloudbuild_cosign.sh

This flag was changed in v0.3.1
Signed-off-by: Jake Sanders <jsand@google.com>

`-kms` -> `-key`

---

cloudbuild.yaml

Signed-off-by: Jake Sanders <jsand@google.com>

stop double signing images, use only cosign v0.5.0

---

README.md

I've noticed a common theme among messages in the #distroless slack channel is people asking whether people use distroless (either to prove to their team it's worth using, or to help convince themselves to look into it).
It just so happens some fairly high profile projects use distroless. 😄

add users to README

---

.github/workflows/ci-cache.yaml
gcscache/Makefile
gcscache/README.md
gcscache/cmd/sync.go

Update bucket name, add simple ci

---

gcscache/cloudbuild.yaml

Add subdir path for cloudbuild

---

cloudbuild_cosign.sh
cloudbuild_docker.sh

Update cloud build for manifestlist + cosign

---

checksums.bzl
package_bundle_amd64_debian11.versions
package_bundle_arm64_debian11.versions
package_bundle_arm_debian11.versions
package_bundle_ppc64le_debian11.versions
package_bundle_s390x_debian11.versions

I don't know what was happening in CI, but just a manual run incase something weird happened.

Manual run of update snapshots

---

.github/workflows/update-deb-package-snapshots.yml

Need to change (I need to submit as well I think?) the cron syntax to transfer notifications to me.

Minor change to cron syntax

---

gcscache/internal/dpkg/package_index.go
gcscache/internal/dpkg/package_index_test.go

I must've accidentally fudged the url right before I submitted

Fix debian security InRelease url

---

BUILD
cloudbuild.yaml
hack/print-workspace-status.sh

This way we can use an insecure registry for getting digests when generating provenance

Make registry configurable with env var

---

cloudbuild.yaml

Ref #821 
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

Bump cosign to v1.1.0

---

java/README.md

Update java readme (remove debian9/java8 images)

---

cloudbuild.yaml

@dlorenc created this serviceaccount earlier in `distroless`, so this should work (famous last words, right?)

Add the keyless signing flow with GCB

---

gcscache/cmd/sync.go

Instead of the path to the latest Packages.xz, makes migration and
parsing a bit easier
```
indexes/bullseye-security-amd64/3122478ed84ecd514120f13c5bfff93318fab2ed8d3f69a5b473a0fe77c3e0b8/Packages.xz
vs
3122478ed84ecd514120f13c5bfff93318fab2ed8d3f69a5b473a0fe77c3e0b8
```

Only write sha to latest

---

provenance/distroless-provenance-task.yaml

Rename step in provenance task

---

.github/workflows/update-deb-package-snapshots.yml

Also pin actions versions to hashes

Fix pull requestion creation

---

.github/workflows/update-deb-package-snapshots.yml

github_token -> token

---

BUILD

Publish cc images for debian11 (bullseye).

Publish cc-debian11 images

---

BUILD
base/BUILD
base/distro.bzl
cacerts/BUILD
cc/BUILD
cloudbuild_cosign.sh
cloudbuild_docker.sh
examples/java/testdata/hello_nonroot_debian11.yaml
examples/java/testdata/hello_root_debian11.yaml
experimental/python3/BUILD
java/BUILD
java/jetty/BUILD
locale/BUILD
nodejs/BUILD

- remove special casing for DISTROS
- publish python3.9-deb11
- some pythong2.7 cleanup
- sign java images

Update debian11 builds housekeeping

---

BUILD

Update defaults to debian11

---

checksums.bzl
package_bundle_amd64_debian10.versions
package_bundle_amd64_debian11.versions
package_bundle_arm64_debian10.versions
package_bundle_arm64_debian11.versions
package_bundle_arm_debian10.versions
package_bundle_arm_debian11.versions
package_bundle_ppc64le_debian10.versions
package_bundle_ppc64le_debian11.versions
package_bundle_s390x_debian10.versions
package_bundle_s390x_debian11.versions

Bumping packages to latest stable versions

Bumping packages to latest stable versions

---

README.md
cloudbuild.yaml

- update cosign to use release v1.3.1

update cosign to use release v1.3.1

---

java/BUILD

build arm java image debug image with right symlink

---

SUPPORT_POLICY.md

Please comment on draft with reasoning on why support should be extended/retracted

A rough idea on how support will look for images.

---

java/jre_ver.bzl
java/testdata/java17_debian11.yaml
java/testdata/java17_debug_debian11.yaml

Update jre_ver macro to correct versions

---

base/BUILD
base/base.bzl
base/distro.bzl
cacerts/BUILD
cc/BUILD
examples/cc/BUILD
examples/java/BUILD
examples/nodejs/BUILD
examples/nonroot/BUILD
experimental/python3/BUILD
java/BUILD
java/jetty/BUILD
locale/BUILD
nodejs/BUILD

use distro instead of distro_suffix

---

provenance/.gitignore

remove accidental provenance binary

---

cacerts/BUILD
java/BUILD

kinda just limits the scope of this goal

move java cacert generation

---

README.md

Use "Container Images" instead of "Docker Images"

---

.github/workflows/ci.yaml
cloudbuild.yaml
updateWorkspaceSnapshots.sh

add retries when fetching deps for ci, publish and update 

---

cloudbuild_cosign.sh
cloudbuild_docker.sh

update python3:* manifest lists

---

cloudbuild_docker.sh

oops, add missing minus

---

BUILD
cloudbuild_cosign.sh

remove legacy java tags

---

examples/nodejs/Dockerfile
examples/nodejs/node-express/Dockerfile
examples/nodejs/node-express/package.json
nodejs/README.md

Upgrade Node 16 to 18 in documentation

---

updateWorkspaceSnapshots.sh

Actually fail if we don't succesfully update

---

WORKSPACE

- jetty-distribution-9.4.48.v20220622
solves #997

Update jetty version

---

debian_package_manager/internal/deb/snapshot.go

Fix debian snapshot url

---

node_archives.bzl
nodejs/testdata/nodejs18.yaml

Updates nodejs 18 images from v18.9.1 to v18.10.0

Bump nodejs 18

---

cloudbuild.yaml

Cosign needs up an update for the new tuf updates.

Update cosign version in cloudbuild.yaml

---

examples/nodejs/Dockerfile
examples/nodejs/node-express/Dockerfile

Depends on #1086, once it is merged I will rebase and make sure tests are working

Update nodejs examles to use the new images

---

BUILD
README.md
cloudbuild_cosign.sh
cloudbuild_docker.sh
examples/nodejs/BUILD
examples/nodejs/testdata/hello.yaml
nodejs/BUILD

I came across #892, and thought I'd give it a go to add `nonroot` images for node
Closes #892

Add `nonroot` to nodejs images

---

.github/workflows/ci.yaml

Fix https://github.com/GoogleContainerTools/distroless/issues/1171

split CI job and resolve lack of disk space

---

BUILD
cloudbuild_cosign.sh
cloudbuild_docker.sh

Move base-nossl out of preview

---

cloudbuild_cosign.sh
cloudbuild_jq.sh

Keyless sign images with separate cosign calls

---

node_archives.bzl
nodejs/testdata/nodejs14.yaml
nodejs/testdata/nodejs16.yaml
nodejs/testdata/nodejs18.yaml

More information https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/

2023-02-16 Security releases for nodejs 14, 16 and 18

---

examples/nodejs/Dockerfile
examples/nodejs/node-express/Dockerfile

Update the node example to nodejs20

---

private/pkg/dpkg_status.go
private/remote/debian_archive.bzl

Fixes https://github.com/GoogleContainerTools/distroless/issues/1304

Fix debian compression assumptions

---

README.md

Add architecture suffixes to readme

---

node_archives.bzl
nodejs/testdata/nodejs20.yaml

https://github.com/nodejs/node/releases/tag/v20.4.0

Node.js v20.4.0

---

.github/workflows/ci.yaml

I think two heavy ci actions were adding to eachothers cache? possibly?

Maybe fix caching issue in ci

---

base/base.bzl
checksums.bzl

Add missing CPU variant for all ARM images.
Closes: #1382

Add missing CPU variant for all ARM images

---

BUILD
README.md
node_archives.bzl
nodejs/BUILD

Added arm, s390x and ppc64le support for nodejs

---

base/testdata/debug.yaml
busybox_archives.bzl

Upgrade busybox to 1.36.1

---

.github/workflows/buildifier.yaml
.github/workflows/image-check.yaml
private/oci/sign_and_push.bzl
private/tools/BUILD.bazel
private/tools/diff.bash

This implements an image diffing pipeline where images built with changes and checked against the images built at HEAD.

ci: implement image diff pipeline

---

README.md

`verifyable` -> [`verifiable`](https://www.merriam-webster.com/dictionary/verifiable)

docs: README.md misspelling

---

WORKSPACE

Picking up a fix in rules_distroless https://github.com/GoogleContainerTools/rules_distroless/pull/28

chore: upgrade rules_distroless@0.3.2

---

.github/workflows/image-check.yaml
BUILD
README.md
SUPPORT_POLICY.md
node_archives.bzl
nodejs/BUILD
nodejs/README.md
nodejs/testdata/nodejs22.yaml

Adds nodejs 20, which is the new LTS version

Add nodejs 22

---

node_archives.bzl
nodejs/testdata/nodejs22.yaml

Bump nodejs22 to `22.5.1`

---

MODULE.bazel

fix: register a default toolchain with root ignored

---

private/oci/sign_and_push.bzl

Fixes https://github.com/GoogleContainerTools/distroless/issues/1755
Changes copy to tag because 
> We can skip layer existence checks because we know the manifest already exists. This makes "tag" slightly faster than "copy".

fix:tag the image with first tag  after pushing using digest ref

---

README.md

- removed duplicate "the the"
- fixed spelling of "infrastructure"
- fixed spelling of "ephemeral"

Update README.md with minor typo fixes

---

MODULE.bazel.lock
nodejs/testdata/nodejs20.yaml
nodejs/testdata/nodejs22.yaml
nodejs/testdata/nodejs24.yaml
private/extensions/node.bzl

https://nodejs.org/en/blog/vulnerability/may-2025-security-releases

Nodejs May 2025 security releases

---

scripts/update_java_archives.sh

Order generated java archive rules
